# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: ksoft.links::lang.controller.form.items.title

# Model Form Field configuration
form: $/ksoft/links/models/linkitem/fields.yaml

# Model Class name
modelClass: Ksoft\Links\Models\LinkItem

# Default redirect location
defaultRedirect: ksoft/links/linkitems

# Create page
create:
    title        : ksoft.links::lang.controller.form.items.create
    redirect     : ksoft/links/linkitems/update/:id
    redirectClose: ksoft/links/linkitems
    flashSave    : ksoft.links::lang.controller.form.items.flashCreate

# Update page
update:
    title        : ksoft.links::lang.controller.form.items.update
    redirect     : ksoft/links/linkitems
    redirectClose: ksoft/links/linkitems
    flashSave    : ksoft.links::lang.controller.form.items.flashUpdate
    flashDelete  : ksoft.links::lang.controller.form.items.flashDelete
