# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Links
    modelClass: Ksoft\Links\Models\LinkItemImport
    list: $/ksoft/links/models/linkitemimport/columns.yaml
    redirect: ksoft/links/linkitems
    permissions: ksoft.links.import_export
